import {SCHEMA,visibleFields,SERVICE_OPTIONS,evaluateRules,validateAll} from './engine.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const escapeHTML=escape;
const titleCase=key=>Object.fromEntries(SERVICE_OPTIONS)[key]||key;
function fieldValue(field,data){const v=data[field.key];if(Array.isArray(v))return v.map(titleCase).join(', ');if(field.type==='radio'||field.type==='select')return field.options.find(o=>o.value===v)?.label||String(v||'');return String(v??'').trim()||'[Pendiente]';}
export function documentSections(draft){return SCHEMA.slice(0,-1).map((step,i)=>({title:`${i+1}. ${step.title}`,items:visibleFields(i,draft.data).map(f=>({label:f.label,value:fieldValue(f,draft.data)}))}));}
export function renderDocument(draft){
  const alerts=evaluateRules(draft.data),issues=validateAll(draft.data);
  return `<article class="paper" lang="es"><div class="paper-top"><span class="paper-brand">ASSISTCONTRACT / 2.0</span><span>BORRADOR NO FIRMABLE</span></div><h1>Borrador de acuerdo de servicios</h1><p class="paper-subtitle">Expediente ${escape(draft.id)} · Versión ${draft.version} · Emitido ${new Date().toLocaleDateString('es-ES')}</p><div class="document-warning"><strong>Documento orientativo.</strong> No acredita identidad, firma, validez de cláusulas ni cumplimiento de mínimos laborales. No debe firmarse sin revisión jurídica aplicable.</div>${documentSections(draft).map(section=>`<section class="paper-section"><h2>${escape(section.title)}</h2><dl>${section.items.map(item=>`<div><dt>${escape(item.label)}</dt><dd>${escape(item.value)}</dd></div>`).join('')}</dl></section>`).join('')}<section class="paper-section"><h2>Validaciones pendientes</h2>${issues.length?`<p>${issues.length} campos necesitan corrección.</p>`:'<p>Campos estructurales completados. La verificación jurídica continúa pendiente.</p>'}<ul>${alerts.map(a=>`<li><strong>${escape(a.title)}:</strong> ${escape(a.detail)}</li>`).join('')}</ul></section><footer class="paper-footer">Generado por AssistContract · Documento no firmable · Requiere revisión profesional.</footer></article>`;
}
export function asText(draft){return ['ASSISTCONTRACT 2.0 · BORRADOR NO FIRMABLE',`Expediente: ${draft.id}`,`Versión: ${draft.version}`,'',...documentSections(draft).flatMap(s=>[s.title,...s.items.map(i=>`${i.label}: ${i.value}`),'']),...evaluateRules(draft.data).map(a=>`[${a.level}] ${a.title}: ${a.detail} | ${a.url}`),'','REVISIÓN JURÍDICA Y FIRMA PENDIENTES.'].join('\n');}
export function asJSON(draft){return JSON.stringify({...draft,format:'assistcontract',schemaVersion:2,exportedAt:new Date().toISOString(),status:'borrador'},null,2);}
export function asHTML(draft){return `<!doctype html><html lang="es"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src &#39;none&#39;; style-src &#39;unsafe-inline&#39;; img-src data:; base-uri &#39;none&#39;; form-action &#39;none&#39;"><title>AssistContract - borrador</title><style>body{font:15px/1.6 system-ui;color:#1d2833;max-width:820px;margin:40px auto;padding:0 20px}h1{font-size:30px}h2{font-size:19px;border-bottom:1px solid #ddd;padding-bottom:8px}.paper-top,.paper-subtitle{color:#536172}.paper-top{display:flex;justify-content:space-between;font-size:12px}.document-warning{border:2px solid #ac5035;background:#fff6f2;padding:16px;margin:20px 0}.paper-section{margin:30px 0}dl>div{display:grid;grid-template-columns:40% 60%;padding:6px 0;border-bottom:1px solid #eee}dt{color:#627080}dd{margin:0;white-space:pre-wrap}.paper-footer{border-top:1px solid #ddd;padding:16px 0;font-size:12px}@media print{body{margin:0;padding:0}}</style>${renderDocument(draft)}</html>`;}
export function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
